import type { Model } from '@local-ai/shared';

export const CURATED_MODELS: Model[] = [
  {
    id: 'smollm2-135m-instruct',
    name: 'SmolLM2 135M Instruct',
    publisher: 'HuggingFaceTB / bartowski',
    description: 'Ultra-lightweight 135M parameter language model optimized for rapid local testing and resource-constrained environments.',
    parameterCount: '135M',
    capabilities: ['TEXT_GENERATION', 'CHAT'],
    tags: ['lightweight', 'compact', 'fast'],
    defaultVariantId: 'smollm2-135m-q8_0',
    variants: [
      {
        id: 'smollm2-135m-q8_0',
        name: 'Q8_0 High Precision',
        quantization: 'Q8_0',
        format: 'gguf',
        sizeBytes: 144_811_360, // ~138 MB
        downloadUrl: 'https://huggingface.co/bartowski/SmolLM2-135M-Instruct-GGUF/resolve/main/SmolLM2-135M-Instruct-Q8_0.gguf',
        contextLength: 2048,
        estimatedRAMBytes: 350 * 1024 * 1024,
        estimatedVRAMBytes: 250 * 1024 * 1024,
        gpuLayers: 32,
      },
    ],
  },
  {
    id: 'qwen2.5-0.5b-instruct',
    name: 'Qwen 2.5 0.5B Instruct',
    publisher: 'Qwen',
    description: 'Compact 0.5B parameter multilingual model with outstanding reasoning capabilities for its size.',
    parameterCount: '0.5B',
    capabilities: ['TEXT_GENERATION', 'CHAT'],
    tags: ['multilingual', 'fast', 'general'],
    defaultVariantId: 'qwen2.5-0.5b-q4_k_m',
    variants: [
      {
        id: 'qwen2.5-0.5b-q4_k_m',
        name: 'Q4_K_M Balanced',
        quantization: 'Q4_K_M',
        format: 'gguf',
        sizeBytes: 491_400_032, // ~468 MB
        downloadUrl: 'https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct-GGUF/resolve/main/qwen2.5-0.5b-instruct-q4_k_m.gguf',
        contextLength: 4096,
        estimatedRAMBytes: 800 * 1024 * 1024,
        estimatedVRAMBytes: 600 * 1024 * 1024,
        gpuLayers: 24,
      },
    ],
  },
  {
    id: 'llama-3.2-1b-instruct',
    name: 'Llama 3.2 1B Instruct',
    publisher: 'Meta',
    description: 'Meta lightweight 1B model optimized for on-device reasoning, tool use, and chat.',
    parameterCount: '1B',
    capabilities: ['TEXT_GENERATION', 'CHAT'],
    tags: ['meta', 'lightweight', 'assistant'],
    defaultVariantId: 'llama-3.2-1b-q4_k_m',
    variants: [
      {
        id: 'llama-3.2-1b-q4_k_m',
        name: 'Q4_K_M Balanced',
        quantization: 'Q4_K_M',
        format: 'gguf',
        sizeBytes: 808_000_000,
        downloadUrl: 'https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q4_K_M.gguf',
        contextLength: 8192,
        estimatedRAMBytes: 1_400_000_000,
        estimatedVRAMBytes: 1_100_000_000,
        gpuLayers: 32,
      },
    ],
  },
  {
    id: 'llama-3.2-3b-instruct',
    name: 'Llama 3.2 3B Instruct',
    publisher: 'Meta',
    description: 'Powerful 3B parameter model delivering top-tier performance for edge computing and local servers.',
    parameterCount: '3B',
    capabilities: ['TEXT_GENERATION', 'CHAT'],
    tags: ['meta', 'popular', 'general'],
    defaultVariantId: 'llama-3.2-3b-q4_k_m',
    variants: [
      {
        id: 'llama-3.2-3b-q4_k_m',
        name: 'Q4_K_M Balanced',
        quantization: 'Q4_K_M',
        format: 'gguf',
        sizeBytes: 2_020_000_000,
        downloadUrl: 'https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q4_K_M.gguf',
        contextLength: 8192,
        estimatedRAMBytes: 3_200_000_000,
        estimatedVRAMBytes: 2_600_000_000,
        gpuLayers: 32,
      },
    ],
  },
  {
    id: 'phi-3.5-mini-instruct',
    name: 'Phi-3.5 Mini Instruct',
    publisher: 'Microsoft',
    description: 'Microsoft 3.8B parameter model featuring exceptional mathematical and logic reasoning capability.',
    parameterCount: '3.8B',
    capabilities: ['TEXT_GENERATION', 'CHAT'],
    tags: ['microsoft', 'reasoning', 'coding'],
    defaultVariantId: 'phi-3.5-mini-q4_k_m',
    variants: [
      {
        id: 'phi-3.5-mini-q4_k_m',
        name: 'Q4_K_M Balanced',
        quantization: 'Q4_K_M',
        format: 'gguf',
        sizeBytes: 2_390_000_000,
        downloadUrl: 'https://huggingface.co/bartowski/Phi-3.5-mini-instruct-GGUF/resolve/main/Phi-3.5-mini-instruct-Q4_K_M.gguf',
        contextLength: 4096,
        estimatedRAMBytes: 3_800_000_000,
        estimatedVRAMBytes: 3_100_000_000,
        gpuLayers: 33,
      },
    ],
  },
  {
    id: 'mistral-7b-instruct-v0.3',
    name: 'Mistral 7B Instruct v0.3',
    publisher: 'Mistral AI',
    description: 'Industry-standard 7B parameter open-weights workhorse with high accuracy and 32k context support.',
    parameterCount: '7B',
    capabilities: ['TEXT_GENERATION', 'CHAT'],
    tags: ['mistral', 'standard', 'production'],
    defaultVariantId: 'mistral-7b-q4_k_m',
    variants: [
      {
        id: 'mistral-7b-q4_k_m',
        name: 'Q4_K_M Balanced',
        quantization: 'Q4_K_M',
        format: 'gguf',
        sizeBytes: 4_370_000_000,
        downloadUrl: 'https://huggingface.co/bartowski/Mistral-7B-Instruct-v0.3-GGUF/resolve/main/Mistral-7B-Instruct-v0.3-Q4_K_M.gguf',
        contextLength: 8192,
        estimatedRAMBytes: 6_800_000_000,
        estimatedVRAMBytes: 5_500_000_000,
        gpuLayers: 33,
      },
    ],
  },
  {
    id: 'deepseek-r1-distill-qwen-7b',
    name: 'DeepSeek R1 Distill Qwen 7B',
    publisher: 'DeepSeek',
    description: 'State-of-the-art distilled reasoning model exhibiting advanced chain-of-thought problem solving.',
    parameterCount: '7B',
    capabilities: ['TEXT_GENERATION', 'CHAT'],
    tags: ['deepseek', 'reasoning', 'math'],
    defaultVariantId: 'deepseek-r1-7b-q4_k_m',
    variants: [
      {
        id: 'deepseek-r1-7b-q4_k_m',
        name: 'Q4_K_M Balanced',
        quantization: 'Q4_K_M',
        format: 'gguf',
        sizeBytes: 4_680_000_000,
        downloadUrl: 'https://huggingface.co/bartowski/DeepSeek-R1-Distill-Qwen-7B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-7B-Q4_K_M.gguf',
        contextLength: 8192,
        estimatedRAMBytes: 7_200_000_000,
        estimatedVRAMBytes: 5_800_000_000,
        gpuLayers: 33,
      },
    ],
  },
];
